name: Auto Check data

on:
  schedule:
    # Berjalan otomatis setiap 6 jam
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run M3U Checker Script
        run: python check_data_system.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add system_data.dt
          git diff --cached --quiet || (
            git commit -m "Update live channels playlist"
            git push
          )
