name: NSTV Auto Clean Playlist

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  clean-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run cleaner script
        # Sesuaikan dengan nama file python Anda di GitHub
        run: python nstv_cleaner.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add system_config_v3.data
          git commit -m "Total Auto-clean (V3): Updated playlists safely with Android headers" || echo "No changes to commit"
          git push
