name: Auto Check M3U Playlist

on:
  schedule:
    # Berjalan otomatis setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch: # Tombol manual untuk menjalankan kapan saja

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run M3U Checker Script
      run: python check_data_system.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add live_channels.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update live channels playlist" && git push)
